"use strict";
exports.__esModule = true;
var Cliente_1 = require("./classes/Cliente");
var Conta_1 = require("./classes/Conta");
var valorDeposito = 100.0;
var valorSaque = 50.0;
var valorTransferencia = 200.0;
var cliente = new Cliente_1.Cliente("Fernando", "111.222.333-20", "f@f.com");
var clienteDestino = new Cliente_1.Cliente("Jo\u00E3o", "999.999999-20", "r@r.com");
var conta = new Conta_1.Conta(cliente, "1999", "456", 100.0);
var contaDestino = new Conta_1.Conta(cliente, "666", "777", 1000.0);
console.log("saldo inicial da conta " + conta.numero + " \u00E9:", conta.getSaldo());
console.log("saldo inicial da contaDestino " + contaDestino.numero + " \u00E9:", contaDestino.getSaldo());
console.log("depositando na conta origem: " + conta.numero + " o valor: " + valorDeposito);
conta.depositar(valorDeposito);
console.log("sacando conta origem: " + conta.numero + " o valor: " + valorSaque);
conta.sacar(valorSaque);
console.log("saldo da conta " + conta.numero + " \u00E9:", conta.getSaldo());
console.log("saldo da contaDestino " + contaDestino.numero + " \u00E9:", contaDestino.getSaldo());
console.log("Transferindo da conta origem " + conta.numero + " para conta destino " + contaDestino.numero);
conta.transferir(valorTransferencia, contaDestino);
console.log("saldo da conta de origem: " + conta.numero, conta.getSaldo());
console.log("saldo conta destino: " + contaDestino.numero, contaDestino.getSaldo());
